# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node_msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='node_msg.proto',
  package='nodes',
  syntax='proto2',
  serialized_pb=_b('\n\x0enode_msg.proto\x12\x05nodes\";\n\x08\x45lection\x12\x0f\n\x07node_id\x18\x01 \x02(\x05\x12\x0c\n\x04type\x18\x02 \x02(\t\x12\x10\n\x08msg_body\x18\x03 \x02(\t')
)




_ELECTION = _descriptor.Descriptor(
  name='Election',
  full_name='nodes.Election',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id', full_name='nodes.Election.node_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='nodes.Election.type', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg_body', full_name='nodes.Election.msg_body', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['Election'] = _ELECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Election = _reflection.GeneratedProtocolMessageType('Election', (_message.Message,), dict(
  DESCRIPTOR = _ELECTION,
  __module__ = 'node_msg_pb2'
  # @@protoc_insertion_point(class_scope:nodes.Election)
  ))
_sym_db.RegisterMessage(Election)


# @@protoc_insertion_point(module_scope)
